# Generated by Django 4.1 on 2022-09-17 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_has_percentage_discount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='has_percentage_discount',
            new_name='has_discount',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price_after_percentage_discount',
            new_name='price_after_discount',
        ),
    ]
