# Generated by Django 4.1 on 2022-09-17 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_rename_has_percentage_discount_product_has_discount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price_after_discount',
            new_name='price_before_discount',
        ),
    ]
