# Generated by Django 4.1 on 2022-09-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_rename_price_after_discount_product_price_before_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='percentage_days_left',
        ),
        migrations.AddField(
            model_name='product',
            name='discount_days_left',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='percentage_off',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_before_discount',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
