# Generated by Django 4.1 on 2022-09-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_product_percentage_days_left_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_days_left',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='percentage_off',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_before_discount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
