# Generated by Django 4.1 on 2022-12-13 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_cartorder_cartorderitems'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartorder',
            options={'verbose_name_plural': 'Orders'},
        ),
    ]
